return {
  "folke/trouble.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  cmd = {
    "Trouble",
    "TroubleToggle",
  },
  keys = {
    -- Usando <leader>x para Trouble (evita conflitos)
    { "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", desc = "Diagnósticos (Trouble)" },
    { "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", desc = "Diagnósticos do Buffer" },
    { "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>", desc = "Símbolos (Trouble)" },
    { "<leader>xL", "<cmd>Trouble loclist toggle<cr>", desc = "Location List" },
    { "<leader>xQ", "<cmd>Trouble qflist toggle<cr>", desc = "Quickfix List" },
  },
  opts = {
    position = "bottom",
    height = 10,
    width = 50,
    icons = true,
    mode = "diagnostics",
    group = true,
    padding = true,
    action_keys = {
      close = "q",
      cancel = "<esc>",
      refresh = "r",
      jump = { "<cr>", "<tab>" },
      open_split = { "<c-x>" },
      open_vsplit = { "<c-v>" },
      open_tab = { "<c-t>" },
      jump_close = { "o" },
      toggle_mode = "m",
      toggle_preview = "P",
      hover = "K",
      preview = "p",
      previous = "k",
      next = "j",
    },
    signs = {
      error = "",
      warning = "",
      hint = "",
      information = "",
      other = "",
    },
    use_diagnostic_signs = false,
  },
}
